[package]
name = "twitch_api2" 
version = "0.2.0"
authors = ["Emil Gardström <emil.gardstrom@gmail.com>"] 
edition = "2018" 
repository = "https://github.com/Emilgardis/twitch_utils" 
license = "MIT OR Apache-2.0" 
description = "Library for talking with the new Twitch API aka. \"Helix\" and TMI." 
keywords = ["oauth", "twitch", "async", "asynchronous", "api"] 
documentation = "https://docs.rs/twitch_api2/0.1.0" 
readme = "README.md" 

[dependencies]
typed-builder = "0.6.0"
thiserror = "1.0.20"
twitch_oauth2 = { version = "^0.3.0"}
serde = { version = "1.0.114", features = ["derive"] }
serde_derive = "1.0.114"
serde_urlencoded = "0.6.1"
async-trait = "0.1.36"
serde_json = "1.0.57"
reqwest = "0.10.7"
url = "2.1.1"
slog = "2.5.2"
tokio = { version = "0.2.22", features = ["time"] }
[features]
default = []

[dev-dependencies]
tokio = { version = "0.2.22", features = ["rt-threaded", "macros"] }
dotenv = "0.15.0"
